development:
  adapter: postgresql
  database: because_we_care_dev
  encoding: unicode
  pool: 10
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: because_we_care_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: because_we_care_production
  pool: 5
  username:
  password:
